name: BlockyJockey
version: 0.0-ALPHA
author: Syst3ms
main: io.github.syst3ms.blockyhockey.BlockyHockey

commands:
  team:
    description: 'team'
  teams:
    description: 'teams'
  timertest:
    description: 'timertest'